### ISSUE TITLE
на первой странице / надо календарь сделать

### ISSUE THREAD

**Issue by matveynator** [matveynator/chicha#27]
на первой странице / надо календарь сделать
далее нажимаем дату попадаем на список заездов по дням и трассам
дажее открываем результат гонки как /api/laps/results/byraceid/1
и подробнее детализацию /api/laps/byraceid/1
и при нажатии на TagID или Имя гонщика смотрим детализацию по конкретному гонщику

**Comment by matveynator** [comment]
https://www.bootstrap-year-calendar.com/?ref=jQueryCards.com

**Comment by fess932** [comment]
Детализация по гонщикам откуда будет браться? Просто интересно, пока только tagID ?

**Comment by fess932** [comment]
Может какую то форму с заполнением данных о гонщиках по tagid сделать

**Comment by fess932** [comment]
#28 in progress

**Comment by matveynator** [comment]
да надо делать личную страницу гонщика
там его имя фамилия возраст класс/кубатура фотография телефон телеграм (чтобы слать нотификации) 
и документы чтобы мог приложить (лицензия/страховка)
